language: objective-c

osx_image: xcode8

before_install:
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent

script:
    - pod install
    - xcodebuild -workspace Codeditor-IOS.xcworkspace -scheme 'Codeditor-IOS' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
